options:
  profile:
    description: |
      Profile representing the scope of deployment, and used to enable high-level customization of
      sys-configs. Allowed values are: “production” and “testing”
    type: string
    default: testing
