#!/usr/bin/env python3

"""Profile setting for OS configs."""


TESTING_PROFILE = {"GRUB_CMDLINE_LINUX_DEFAULT": "$GRUB_CMDLINE_LINUX_DEFAULT hugepagesz=500M"}
PRODUCTION_PROFILE = {"GRUB_CMDLINE_LINUX_DEFAULT": "$GRUB_CMDLINE_LINUX_DEFAULT hugepagesz=1G"}
